### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by iffy** [iffy/ppo#26]
On some big output (maybe?  seems like the problem), I get broken pipes.  Perhaps I shouldn't read and write the whole thing at once :)

I saw it when doing `cat /tmp/nmap.xml | ppo -f grep | grep process`

**Comment by iffy** [comment]
It turns out that the `grep` really had closed the pipe because the output of `ppo -f grep` contained some non-ascii characters.  This is the full output:

```
Binary file (standard input) matches
Traceback (most recent call last):
  File "/usr/local/bin/ppo", line 6, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/ppo/runner.py", line 75, in run
    giganticGrep(parsed, sys.stdout)
  File "/usr/local/lib/python2.7/dist-packages/ppo/output.py", line 52, in giganticGrep
    outstream.write(line + '\n')
IOError: [Errno 32] Broken pipe
```

You can see the first line (which I had missed) shows that grep found a match and, since it thinks it's a binary file, closed the pipe.  In this case, I think the error should just be suppressed, perhaps as described here: http://newbebweb.blogspot.com/2012/02/python-head-ioerror-errno-32-broken.html  or else with a try/except block.
